name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run linter
        run: |
          npm install
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: |
          echo "skipping"
          # npm install
          # npm run test:cov

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v3
      - name: run build
        run: |
          npm install
          npm run build

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rethinkdb/admin:main

      - name: Build and push latest
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            rethinkdb/admin:latest
            rethinkdb/admin:${{ github.ref_name }}
